FROM node:18-alpine AS builder

WORKDIR /usr/src/app

COPY package.json ./

COPY yarn.lock ./

RUN yarn 

COPY tsconfig.json ./

COPY . .

RUN yarn run build

FROM node:18-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/yarn.lock ./

RUN yarn install --production

EXPOSE 3000

CMD ["node", "dist/index.js"]
